package p4.domain;

import java.io.Serializable;
import java.util.Collection;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.Min;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 *
 * @author reget.kalamees
 */
@Entity
public class AdminYksus implements Serializable {
   
    //CREATE TABLE RIIGI_ADMIN_YKSUS ( 
    //riigi_admin_yksus_ID INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL,
    //avaja VARCHAR(32) NOT NULL,
    //avatud DATE NOT NULL, 
    //muutja VARCHAR(32) NOT NULL,
    //muudetud DATE NOT NULL, 
    //sulgeja VARCHAR(32),
    //suletud DATE NOT NULL,
    //kood VARCHAR(20),
    //nimetus VARCHAR(100),
    //kommentaar LONGVARCHAR, 
    //alates DATE NOT NULL,
    //kuni DATE NOT NULL, 
    //riigi_admin_yksuse_lik_id INTEGER NOT NULL,
    //PRIMARY KEY (riigi_admin_yksus_ID), 
    //FOREIGN KEY (riigi_admin_yksuse_lik_id) REFERENCES RIIGI_ADMIN_YKSUSE_LIIK ON DELETE RESTRICT )"
    //selleks, et primary keyd algaks nr 1
    
    /* seda saab kasutada alles siis, kui db tabel on olemas
    @SequenceGenerator(name = "seq", initialValue = 1, allocationSize = 100)
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "seq")
    * 
    */
    private static final long serialVersionUID = 1L;
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "riigi_admin_yksus_ID")
    private Long id;
    
    //TODO - mis siin täpselt juhtub -EAGER kasutada ei saa
    @ManyToMany
    @JoinTable(
	            name = "AdminAlluvus",
    joinColumns = {
        @JoinColumn(name = "ylem_id", referencedColumnName = "riigi_admin_yksus_ID")},
    inverseJoinColumns = {
        @JoinColumn(name = "alluv_id", referencedColumnName = "riigi_admin_yksus_ID")})
    private Collection<AdminYksus> alluvad;
    
    
    
    
    
    @Column(length = 32, nullable = false)
    private String avaja;
    //ajatüüpidele on vajalik see annotatsioon
    
    @Column(nullable = false)
    @Temporal(javax.persistence.TemporalType.DATE)
    private Date avatud;
    @Column(length = 32, nullable = false)
    private String muutja;
    @Temporal(TemporalType.DATE)
    @Column(nullable = false)
    private Date muudetud;
    @Column(length = 32, nullable = false)
    private String sulgeja;
    @Temporal(TemporalType.DATE)
    @Column(nullable = false)
    private Date suletud;
    @Column(length = 20)
    private String kood;
    
    @Column(length = 100)
    @Size(min=2,max=40)  //valideerimise värk
    private String nimetus;
    @Column(length = 32000)
    private String kommentaar;
    @Temporal(TemporalType.DATE)
    @Column(nullable = false)
    private Date alates;
    @Temporal(TemporalType.DATE)
    @Column(nullable = false)
    private Date kuni;
   
    //kas neid on vaja? 
    private String yl_id;
    private String liik_id;
    
    public String getLiik_id() {
		return liik_id;
	}

	public void setLiik_id(String liik_id) {
		this.liik_id = liik_id;
	}
        //kas vaja?
        

	@ManyToOne
     private AdminYksLiik admykId;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @Override
    public int hashCode() {
        int hash = 0;
        hash += (id != null ? id.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the id fields are not set
        if (!(object instanceof AdminYksus)) {
            return false;
        }
        AdminYksus other = (AdminYksus) object;
        if ((this.id == null && other.id != null) || (this.id != null && !this.id.equals(other.id))) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "p4.domain.AdminYksus[ id=" + id + " ]";
    }

    /**
     * @return the avaja
     */
    public String getAvaja() {
        return avaja;
    }

    /**
     * @param avaja the avaja to set
     */
    public void setAvaja(String avaja) {
        this.avaja = avaja;
    }

    /**
     * @return the avatud
     */
    public Date getAvatud() {
        return avatud;
    }

    /**
     * @param avatud the avatud to set
     */
    public void setAvatud(Date avatud) {
        this.avatud = avatud;
    }

    /**
     * @return the muutja
     */
    public String getMuutja() {
        return muutja;
    }

    /**
     * @param muutja the muutja to set
     */
    public void setMuutja(String muutja) {
        this.muutja = muutja;
    }

    /**
     * @return the muudetud
     */
    public Date getMuudetud() {
        return muudetud;
    }

    /**
     * @param muudetud the muudetud to set
     */
    public void setMuudetud(Date muudetud) {
        this.muudetud = muudetud;
    }

    /**
     * @return the sulgeja
     */
    public String getSulgeja() {
        return sulgeja;
    }

    /**
     * @param sulgeja the sulgeja to set
     */
    public void setSulgeja(String sulgeja) {
        this.sulgeja = sulgeja;
    }

    /**
     * @return the suletud
     */
    public Date getSuletud() {
        return suletud;
    }

    /**
     * @param suletud the suletud to set
     */
    public void setSuletud(Date suletud) {
        this.suletud = suletud;
    }

    /**
     * @return the kood
     */
    public String getKood() {
        return kood;
    }

    /**
     * @param kood the kood to set
     */
    public void setKood(String kood) {
        this.kood = kood;
    }

    /**
     * @return the nimetus
     */
    public String getNimetus() {
        return nimetus;
    }

    /**
     * @param nimetus the nimetus to set
     */
    public void setNimetus(String nimetus) {
        this.nimetus = nimetus;
    }

    /**
     * @return the kommentaar
     */
    public String getKommentaar() {
        return kommentaar;
    }

    /**
     * @param kommentaar the kommentaar to set
     */
    public void setKommentaar(String kommentaar) {
        this.kommentaar = kommentaar;
    }

    /**
     * @return the alates
     */
    public Date getAlates() {
        return alates;
    }

    /**
     * @param alates the alates to set
     */
    public void setAlates(Date alates) {
        this.alates = alates;
    }

    /**
     * @return the kuni
     */
    public Date getKuni() {
        return kuni;
    }

    /**
     * @param kuni the kuni to set
     */
    public void setKuni(Date kuni) {
        this.kuni = kuni;
    }

    /**
     * @return the admykId
     */
    public AdminYksLiik getAdmykId() {
        return admykId;
    }

    /**
     * @param admykId the admykId to set
     */
    public void setAdmykId(AdminYksLiik admykId) {
        this.admykId = admykId;
    }

    /**
     * @return the alluvad
     */
    public Collection<AdminYksus> getAlluvad() {
        return alluvad;
    }

    /**
     * @param alluvad the alluvad to set
     */
    public void setAlluvad(Collection<AdminYksus> alluvad) {
        this.alluvad = alluvad;
    }

    /**
     * @return the yl_id
     */
    public String getYl_id() {
        return yl_id;
    }

    /**
     * @param yl_id the yl_id to set
     */
    public void setYl_id(String yl_id) {
        this.yl_id = yl_id;
    }

    
}
